<a href="https://colab.research.google.com/github/ambreenkhurrum-lgtm/ITC/blob/main/dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

data = {'Name': ['Ambreen','Lavania','Sara'],
        'Salary':[2000,3000,4000]}

In [2]:
df=pd.DataFrame(data)

In [3]:
df

      Name  Salary
0  Ambreen    2000
1  Lavania    3000
2     Sara    4000

In [4]:
import pandas as pd

data = {
"Name": ["Amit", "Sara", "John", "Priya", "David"],
"Age": [25, 30, 22, 28, 35],
"City": ["London", "Birmingham", "London", "Coventry", "Manchester"],
"Salary": [30000, 45000, 28000, 40000, 50000]
}

df = pd.DataFrame(data)

print(df)

    Name  Age        City  Salary
0   Amit   25      London   30000
1   Sara   30  Birmingham   45000
2   John   22      London   28000
3  Priya   28    Coventry   40000
4  David   35  Manchester   50000

In [ ]:
Display the complete DataFrame.
Display only the first 3 rows.
Display only the Name column.
Display the Name and Salary columns.
Find all employees whose Age is greater than 25.
Find all employees whose Salary is greater than 40,000.
Find employees who live in London.
Add a new column called Department with these values

In [8]:
print(df)

    Name  Age        City  Salary
0   Amit   25      London   30000
1   Sara   30  Birmingham   45000
2   John   22      London   28000
3  Priya   28    Coventry   40000
4  David   35  Manchester   50000

In [16]:
df.head(3)

   Name  Age        City  Salary
0  Amit   25      London   30000
1  Sara   30  Birmingham   45000
2  John   22      London   28000

In [7]:
df[0:3]

   Name  Age        City  Salary
0  Amit   25      London   30000
1  Sara   30  Birmingham   45000
2  John   22      London   28000

In [9]:
print(df['Name'])

0     Amit
1     Sara
2     John
3    Priya
4    David
Name: Name, dtype: object

In [10]:
print(df[['Name','Salary']])

    Name  Salary
0   Amit   30000
1   Sara   45000
2   John   28000
3  Priya   40000
4  David   50000

In [20]:
print(df[df['Salary']>40000])

    Name  Age        City  Salary Department
1   Sara   30  Birmingham   45000         HR
4  David   35  Manchester   50000         IT

In [15]:
df[df['City']=='London']

   Name  Age    City  Salary
0  Amit   25  London   30000
2  John   22  London   28000

In [18]:
df['Department']=['IT','HR','IT','HR','IT']

In [19]:
df.head()

    Name  Age        City  Salary Department
0   Amit   25      London   30000         IT
1   Sara   30  Birmingham   45000         HR
2   John   22      London   28000         IT
3  Priya   28    Coventry   40000         HR
4  David   35  Manchester   50000         IT