<a href="https://colab.research.google.com/github/ambreenkhurrum-lgtm/ITC/blob/assignment/pandas_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('sales.csv')

In [ ]:
df.head()

,OrderID,Customer,City,Category,Product,Quantity,UnitPrice,Discount,OrderDate,PaymentMethod,Rating
0,1001,Amit,London,Electronics,Headphones,2,45.0,0.1,2026-08-01,Card,4.5
1,1002,Sara,Birmingham,Clothing,Jacket,1,80.0,0.0,2026-08-01,PayPal,4.0
2,1003,John,London,Grocery,Coffee,3,8.5,0.05,2026-08-02,Card,3.5
3,1004,Priya,Coventry,Electronics,Keyboard,1,35.0,0.0,2026-08-02,Card,4.8
4,1005,David,Manchester,Clothing,Shoes,2,60.0,0.15,2026-08-03,Cash,4.1

In [ ]:
# df.to_csv('my_data.csv', index=False)

In [ ]:
4. Part A - DataFrame Basics
1. Display the complete DataFrame.
2. Display the first 5 rows.
3. Display the last 5 rows.

In [ ]:
df

,OrderID,Customer,City,Category,Product,Quantity,UnitPrice,Discount,OrderDate,PaymentMethod,Rating
0,1001,Amit,London,Electronics,Headphones,2,45.0,0.1,2026-08-01,Card,4.5
1,1002,Sara,Birmingham,Clothing,Jacket,1,80.0,0.0,2026-08-01,PayPal,4.0
2,1003,John,London,Grocery,Coffee,3,8.5,0.05,2026-08-02,Card,3.5
3,1004,Priya,Coventry,Electronics,Keyboard,1,35.0,0.0,2026-08-02,Card,4.8
4,1005,David,Manchester,Clothing,Shoes,2,60.0,0.15,2026-08-03,Cash,4.1
5,1006,Emma,Leeds,Grocery,Tea,4,5.0,0.0,2026-08-03,Card,NaN
6,1007,Noah,London,Electronics,Mouse,2,20.0,0.05,2026-08-04,PayPal,4.6
7,1008,Olivia,Coventry,Home,Lamp,1,25.0,0.0,2026-08-04,Card,4.2
8,1009,Liam,Birmingham,Home,Chair,2,55.0,0.1,2026-08-05,Card,3.9
9,1010,Ava,Manchester,Grocery,Rice,5,3.5,0.0,2026-08-05,Cash,4.0
10,1011,Mia,Leeds,Clothing,T-Shirt,3,18.0,0.05,2026-08-06,Card,4.7
11,1012,Ethan,London,Electronics,Monitor,1,180.0,0.1,2026-08-06,PayPal,4.9
12,1013,Sophia,Coventry,Grocery,Milk,6,1.5,0.0,2026-08-07,Card,4.3
13,1014,Lucas,Birmingham,Home,Desk,1,120.0,0.15,2026-08-07,Card,4.4
14,1015,Isla,Manchester,Electronics,Speaker,2,50.0,0.05,2026-08-08,Cash,3.8
15,1016,Jack,Leeds,Clothing,Jeans,2,40.0,0.0,2026-08-08,Card,4.1
16,1017,Grace,London,Home,Cushion,4,12.0,0.1,2026-08-09,PayPal,4.5
17,1018,Leo,Coventry,Electronics,USB Cable,5,6.0,0.0,2026-08-09,Card,4.0
18,1019,Freya,Birmingham,Grocery,Bread,3,2.2,0.0,2026-08-10,Cash,NaN
19,1020,Oscar,Manchester,Home,Shelf,2,45.0,0.05,2026-08-10,Card,4.6
20,1021,Amelia,Leeds,Electronics,Webcam,1,55.0,0.1,2026-08-11,Card,4.7
21,1022,Harry,London,Clothing,Sweater,2,35.0,0.0,2026-08-11,PayPal,3.7
22,1023,Ella,Coventry,Grocery,Eggs,2,3.2,0.0,2026-08-12,Card,4.2
23,1024,George,Birmingham,Electronics,Laptop Stand,1,32.0,0.05,2026-08-12,Card,4.8
24,1025,Chloe,Manchester,Home,Mirror,1,70.0,0.1,2026-08-13,Cash,4.4
25,1026,Arthur,Leeds,Grocery,Pasta,4,2.5,0.0,2026-08-13,Card,3.9
26,1027,Lily,London,Electronics,Power Bank,2,30.0,0.05,2026-08-14,PayPal,4.6
27,1028,Henry,Coventry,Clothing,Coat,1,95.0,0.15,2026-08-14,Card,4.3
28,1029,Evie,Birmingham,Home,Rug,1,65.0,0.0,2026-08-15,Card,4.1
29,1030,Charlie,Manchester,Grocery,Juice,3,2.8,0.0,2026-08-15,Cash,4.0

In [ ]:
df.head(5)

,OrderID,Customer,City,Category,Product,Quantity,UnitPrice,Discount,OrderDate,PaymentMethod,Rating
0,1001,Amit,London,Electronics,Headphones,2,45.0,0.1,2026-08-01,Card,4.5
1,1002,Sara,Birmingham,Clothing,Jacket,1,80.0,0.0,2026-08-01,PayPal,4.0
2,1003,John,London,Grocery,Coffee,3,8.5,0.05,2026-08-02,Card,3.5
3,1004,Priya,Coventry,Electronics,Keyboard,1,35.0,0.0,2026-08-02,Card,4.8
4,1005,David,Manchester,Clothing,Shoes,2,60.0,0.15,2026-08-03,Cash,4.1

In [ ]:
df.tail(5)

,OrderID,Customer,City,Category,Product,Quantity,UnitPrice,Discount,OrderDate,PaymentMethod,Rating
25,1026,Arthur,Leeds,Grocery,Pasta,4,2.5,0.0,2026-08-13,Card,3.9
26,1027,Lily,London,Electronics,Power Bank,2,30.0,0.05,2026-08-14,PayPal,4.6
27,1028,Henry,Coventry,Clothing,Coat,1,95.0,0.15,2026-08-14,Card,4.3
28,1029,Evie,Birmingham,Home,Rug,1,65.0,0.0,2026-08-15,Card,4.1
29,1030,Charlie,Manchester,Grocery,Juice,3,2.8,0.0,2026-08-15,Cash,4.0

In [ ]:
#4. Find the number of rows and columns.
df.shape

(30, 11)

In [ ]:
#5. Display all column names.
df.columns

Index(['OrderID ', 'Customer ', 'City ', 'Category ', 'Product ', 'Quantity ',
       'UnitPrice ', 'Discount ', 'OrderDate ', 'PaymentMethod ', 'Rating '],
      dtype='object')

In [ ]:
 #6. Check the data type of every column.
df.dtypes

OrderID           object
Customer          object
City              object
Category          object
Product           object
Quantity          object
UnitPrice         object
Discount          object
OrderDate         object
PaymentMethod     object
Rating            object
dtype: object

In [ ]:
#7. Use info() to inspect the DataFrame.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   OrderID         30 non-null     object
 1   Customer        30 non-null     object
 2   City            30 non-null     object
 3   Category        30 non-null     object
 4   Product         30 non-null     object
 5   Quantity        30 non-null     object
 6   UnitPrice       30 non-null     object
 7   Discount        30 non-null     object
 8   OrderDate       30 non-null     object
 9   PaymentMethod   30 non-null     object
 10  Rating          28 non-null     object
dtypes: object(11)
memory usage: 2.7+ KB

In [ ]:
#8. Use describe() to generate descriptive statistics.
df.describe()

,OrderID,Customer,City,Category,Product,Quantity,UnitPrice,Discount,OrderDate,PaymentMethod,Rating
count,30,30,30,30,30,30,30,30,30,30,28
unique,30,30,5,4,30,6,27,4,15,3,14
top,1001,Amit,London,Electronics,Headphones,2,45.0,0.0,2026-08-01,Card,4.0
freq,1,1,7,9,1,10,2,14,2,18,4

In [ ]:
df.columns

Index(['OrderID ', 'Customer ', 'City ', 'Category ', 'Product ', 'Quantity ',
       'UnitPrice ', 'Discount ', 'OrderDate ', 'PaymentMethod ', 'Rating '],
      dtype='object')

In [ ]:
#there are spaces in the column names
df.columns = df.columns.str.strip()

In [ ]:
df.columns

Index(['OrderID', 'Customer', 'City', 'Category', 'Product', 'Quantity',
       'UnitPrice', 'Discount', 'OrderDate', 'PaymentMethod', 'Rating'],
      dtype='object')

In [ ]:
#9. Select only Customer, City and Category.
df[['Customer', 'City', 'Category']]

    Customer         City      Category
0      Amit       London   Electronics
1      Sara   Birmingham      Clothing
2      John       London       Grocery
3     Priya     Coventry   Electronics
4     David   Manchester      Clothing
5      Emma        Leeds       Grocery
6      Noah       London   Electronics
7    Olivia     Coventry          Home
8      Liam   Birmingham          Home
9       Ava   Manchester       Grocery
10      Mia        Leeds      Clothing
11    Ethan       London   Electronics
12   Sophia     Coventry       Grocery
13    Lucas   Birmingham          Home
14     Isla   Manchester   Electronics
15     Jack        Leeds      Clothing
16    Grace       London          Home
17      Leo     Coventry   Electronics
18    Freya   Birmingham       Grocery
19    Oscar   Manchester          Home
20   Amelia        Leeds   Electronics
21    Harry       London      Clothing
22     Ella     Coventry       Grocery
23   George   Birmingham   Electronics
24    Chloe   Manchester          Home
25   Arthur        Leeds       Grocery
26     Lily       London   Electronics
27    Henry     Coventry      Clothing
28     Evie   Birmingham          Home
29  Charlie   Manchester       Grocery

In [ ]:
#10. Select only the UnitPrice column as a Series.
df['UnitPrice']

0      45.0
1      80.0
2       8.5
3      35.0
4      60.0
5       5.0
6      20.0
7      25.0
8      55.0
9       3.5
10     18.0
11    180.0
12      1.5
13    120.0
14     50.0
15     40.0
16     12.0
17      6.0
18      2.2
19     45.0
20     55.0
21     35.0
22      3.2
23     32.0
24     70.0
25      2.5
26     30.0
27     95.0
28     65.0
29      2.8
Name: UnitPrice, dtype: object

In [ ]:
#11. Rename Customer to CustomerName.
df.rename(columns = {'Customer':'CustomerName'})

,OrderID,CustomerName,City,Category,Product,Quantity,UnitPrice,Discount,OrderDate,PaymentMethod,Rating
0,1001,Amit,London,Electronics,Headphones,2,45.0,0.1,2026-08-01,Card,4.5
1,1002,Sara,Birmingham,Clothing,Jacket,1,80.0,0.0,2026-08-01,PayPal,4.0
2,1003,John,London,Grocery,Coffee,3,8.5,0.05,2026-08-02,Card,3.5
3,1004,Priya,Coventry,Electronics,Keyboard,1,35.0,0.0,2026-08-02,Card,4.8
4,1005,David,Manchester,Clothing,Shoes,2,60.0,0.15,2026-08-03,Cash,4.1
5,1006,Emma,Leeds,Grocery,Tea,4,5.0,0.0,2026-08-03,Card,NaN
6,1007,Noah,London,Electronics,Mouse,2,20.0,0.05,2026-08-04,PayPal,4.6
7,1008,Olivia,Coventry,Home,Lamp,1,25.0,0.0,2026-08-04,Card,4.2
8,1009,Liam,Birmingham,Home,Chair,2,55.0,0.1,2026-08-05,Card,3.9
9,1010,Ava,Manchester,Grocery,Rice,5,3.5,0.0,2026-08-05,Cash,4.0
10,1011,Mia,Leeds,Clothing,T-Shirt,3,18.0,0.05,2026-08-06,Card,4.7
11,1012,Ethan,London,Electronics,Monitor,1,180.0,0.1,2026-08-06,PayPal,4.9
12,1013,Sophia,Coventry,Grocery,Milk,6,1.5,0.0,2026-08-07,Card,4.3
13,1014,Lucas,Birmingham,Home,Desk,1,120.0,0.15,2026-08-07,Card,4.4
14,1015,Isla,Manchester,Electronics,Speaker,2,50.0,0.05,2026-08-08,Cash,3.8
15,1016,Jack,Leeds,Clothing,Jeans,2,40.0,0.0,2026-08-08,Card,4.1
16,1017,Grace,London,Home,Cushion,4,12.0,0.1,2026-08-09,PayPal,4.5
17,1018,Leo,Coventry,Electronics,USB Cable,5,6.0,0.0,2026-08-09,Card,4.0
18,1019,Freya,Birmingham,Grocery,Bread,3,2.2,0.0,2026-08-10,Cash,NaN
19,1020,Oscar,Manchester,Home,Shelf,2,45.0,0.05,2026-08-10,Card,4.6
20,1021,Amelia,Leeds,Electronics,Webcam,1,55.0,0.1,2026-08-11,Card,4.7
21,1022,Harry,London,Clothing,Sweater,2,35.0,0.0,2026-08-11,PayPal,3.7
22,1023,Ella,Coventry,Grocery,Eggs,2,3.2,0.0,2026-08-12,Card,4.2
23,1024,George,Birmingham,Electronics,Laptop Stand,1,32.0,0.05,2026-08-12,Card,4.8
24,1025,Chloe,Manchester,Home,Mirror,1,70.0,0.1,2026-08-13,Cash,4.4
25,1026,Arthur,Leeds,Grocery,Pasta,4,2.5,0.0,2026-08-13,Card,3.9
26,1027,Lily,London,Electronics,Power Bank,2,30.0,0.05,2026-08-14,PayPal,4.6
27,1028,Henry,Coventry,Clothing,Coat,1,95.0,0.15,2026-08-14,Card,4.3
28,1029,Evie,Birmingham,Home,Rug,1,65.0,0.0,2026-08-15,Card,4.1
29,1030,Charlie,Manchester,Grocery,Juice,3,2.8,0.0,2026-08-15,Cash,4.0

In [ ]:
#12. Change OrderDate to datetime type.
df['OrderDate'] = pd.to_datetime(df['OrderDate'])

In [ ]:
df["Category"] = df["Category"].str.strip()

In [ ]:
#13. Reset the index after making a filtered DataFrame.
filtered_df = df[df['Category'] == 'Electronics']

In [ ]:
filtered_df

,OrderID,Customer,City,Category,Product,Quantity,UnitPrice,Discount,OrderDate,PaymentMethod,Rating
0,1001,Amit,London,Electronics,Headphones,2,45.0,0.1,2026-08-01,Card,4.5
3,1004,Priya,Coventry,Electronics,Keyboard,1,35.0,0.0,2026-08-02,Card,4.8
6,1007,Noah,London,Electronics,Mouse,2,20.0,0.05,2026-08-04,PayPal,4.6
11,1012,Ethan,London,Electronics,Monitor,1,180.0,0.1,2026-08-06,PayPal,4.9
14,1015,Isla,Manchester,Electronics,Speaker,2,50.0,0.05,2026-08-08,Cash,3.8
17,1018,Leo,Coventry,Electronics,USB Cable,5,6.0,0.0,2026-08-09,Card,4.0
20,1021,Amelia,Leeds,Electronics,Webcam,1,55.0,0.1,2026-08-11,Card,4.7
23,1024,George,Birmingham,Electronics,Laptop Stand,1,32.0,0.05,2026-08-12,Card,4.8
26,1027,Lily,London,Electronics,Power Bank,2,30.0,0.05,2026-08-14,PayPal,4.6

In [ ]:
df['City'] = df['City'].str.strip()

In [ ]:
#14. Find all orders from London.
df[df['City']=='London']

,OrderID,Customer,City,Category,Product,Quantity,UnitPrice,Discount,OrderDate,PaymentMethod,Rating
0,1001,Amit,London,Electronics,Headphones,2,45.0,0.1,2026-08-01,Card,4.5
2,1003,John,London,Grocery,Coffee,3,8.5,0.05,2026-08-02,Card,3.5
6,1007,Noah,London,Electronics,Mouse,2,20.0,0.05,2026-08-04,PayPal,4.6
11,1012,Ethan,London,Electronics,Monitor,1,180.0,0.1,2026-08-06,PayPal,4.9
16,1017,Grace,London,Home,Cushion,4,12.0,0.1,2026-08-09,PayPal,4.5
21,1022,Harry,London,Clothing,Sweater,2,35.0,0.0,2026-08-11,PayPal,3.7
26,1027,Lily,London,Electronics,Power Bank,2,30.0,0.05,2026-08-14,PayPal,4.6

In [ ]:
#15. Find all Electronics orders.
df[df['Category']=='Electronics']

,OrderID,Customer,City,Category,Product,Quantity,UnitPrice,Discount,OrderDate,PaymentMethod,Rating
0,1001,Amit,London,Electronics,Headphones,2,45.0,0.1,2026-08-01,Card,4.5
3,1004,Priya,Coventry,Electronics,Keyboard,1,35.0,0.0,2026-08-02,Card,4.8
6,1007,Noah,London,Electronics,Mouse,2,20.0,0.05,2026-08-04,PayPal,4.6
11,1012,Ethan,London,Electronics,Monitor,1,180.0,0.1,2026-08-06,PayPal,4.9
14,1015,Isla,Manchester,Electronics,Speaker,2,50.0,0.05,2026-08-08,Cash,3.8
17,1018,Leo,Coventry,Electronics,USB Cable,5,6.0,0.0,2026-08-09,Card,4.0
20,1021,Amelia,Leeds,Electronics,Webcam,1,55.0,0.1,2026-08-11,Card,4.7
23,1024,George,Birmingham,Electronics,Laptop Stand,1,32.0,0.05,2026-08-12,Card,4.8
26,1027,Lily,London,Electronics,Power Bank,2,30.0,0.05,2026-08-14,PayPal,4.6

In [ ]:
#16. Find orders where Quantity is greater than 2.
df['Quantity'] = df.Quantity.astype('int')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        30 non-null     object
 1   Customer       30 non-null     object
 2   City           30 non-null     object
 3   Category       30 non-null     object
 4   Product        30 non-null     object
 5   Quantity       30 non-null     int64
 6   UnitPrice      30 non-null     object
 7   Discount       30 non-null     object
 8   OrderDate      30 non-null     object
 9   PaymentMethod  30 non-null     object
 10  Rating         28 non-null     object
dtypes: int64(1), object(10)
memory usage: 2.7+ KB

In [ ]:
df[df['Quantity']>2]

,OrderID,Customer,City,Category,Product,Quantity,UnitPrice,Discount,OrderDate,PaymentMethod,Rating
2,1003,John,London,Grocery,Coffee,3,8.5,0.05,2026-08-02,Card,3.5
5,1006,Emma,Leeds,Grocery,Tea,4,5.0,0.0,2026-08-03,Card,NaN
9,1010,Ava,Manchester,Grocery,Rice,5,3.5,0.0,2026-08-05,Cash,4.0
10,1011,Mia,Leeds,Clothing,T-Shirt,3,18.0,0.05,2026-08-06,Card,4.7
12,1013,Sophia,Coventry,Grocery,Milk,6,1.5,0.0,2026-08-07,Card,4.3
16,1017,Grace,London,Home,Cushion,4,12.0,0.1,2026-08-09,PayPal,4.5
17,1018,Leo,Coventry,Electronics,USB Cable,5,6.0,0.0,2026-08-09,Card,4.0
18,1019,Freya,Birmingham,Grocery,Bread,3,2.2,0.0,2026-08-10,Cash,NaN
25,1026,Arthur,Leeds,Grocery,Pasta,4,2.5,0.0,2026-08-13,Card,3.9
29,1030,Charlie,Manchester,Grocery,Juice,3,2.8,0.0,2026-08-15,Cash,4.0

In [ ]:
#17. Find orders where UnitPrice is greater than £50.
df['UnitPrice'] = df.UnitPrice.astype('float')

In [ ]:
df[df['UnitPrice']> 50]

,OrderID,Customer,City,Category,Product,Quantity,UnitPrice,Discount,OrderDate,PaymentMethod,Rating
1,1002,Sara,Birmingham,Clothing,Jacket,1,80.0,0.0,2026-08-01,PayPal,4.0
4,1005,David,Manchester,Clothing,Shoes,2,60.0,0.15,2026-08-03,Cash,4.1
8,1009,Liam,Birmingham,Home,Chair,2,55.0,0.1,2026-08-05,Card,3.9
11,1012,Ethan,London,Electronics,Monitor,1,180.0,0.1,2026-08-06,PayPal,4.9
13,1014,Lucas,Birmingham,Home,Desk,1,120.0,0.15,2026-08-07,Card,4.4
20,1021,Amelia,Leeds,Electronics,Webcam,1,55.0,0.1,2026-08-11,Card,4.7
24,1025,Chloe,Manchester,Home,Mirror,1,70.0,0.1,2026-08-13,Cash,4.4
27,1028,Henry,Coventry,Clothing,Coat,1,95.0,0.15,2026-08-14,Card,4.3
28,1029,Evie,Birmingham,Home,Rug,1,65.0,0.0,2026-08-15,Card,4.1

In [ ]:
#18. Find orders with Discount greater than 0.
df['Discount'] = df.Discount.astype('float')

In [ ]:
df[df['Discount']>0]

,OrderID,Customer,City,Category,Product,Quantity,UnitPrice,Discount,OrderDate,PaymentMethod,Rating
0,1001,Amit,London,Electronics,Headphones,2,45.0,0.10,2026-08-01,Card,4.5
2,1003,John,London,Grocery,Coffee,3,8.5,0.05,2026-08-02,Card,3.5
4,1005,David,Manchester,Clothing,Shoes,2,60.0,0.15,2026-08-03,Cash,4.1
6,1007,Noah,London,Electronics,Mouse,2,20.0,0.05,2026-08-04,PayPal,4.6
8,1009,Liam,Birmingham,Home,Chair,2,55.0,0.10,2026-08-05,Card,3.9
10,1011,Mia,Leeds,Clothing,T-Shirt,3,18.0,0.05,2026-08-06,Card,4.7
11,1012,Ethan,London,Electronics,Monitor,1,180.0,0.10,2026-08-06,PayPal,4.9
13,1014,Lucas,Birmingham,Home,Desk,1,120.0,0.15,2026-08-07,Card,4.4
14,1015,Isla,Manchester,Electronics,Speaker,2,50.0,0.05,2026-08-08,Cash,3.8
16,1017,Grace,London,Home,Cushion,4,12.0,0.10,2026-08-09,PayPal,4.5
19,1020,Oscar,Manchester,Home,Shelf,2,45.0,0.05,2026-08-10,Card,4.6
20,1021,Amelia,Leeds,Electronics,Webcam,1,55.0,0.10,2026-08-11,Card,4.7
23,1024,George,Birmingham,Electronics,Laptop Stand,1,32.0,0.05,2026-08-12,Card,4.8
24,1025,Chloe,Manchester,Home,Mirror,1,70.0,0.10,2026-08-13,Cash,4.4
26,1027,Lily,London,Electronics,Power Bank,2,30.0,0.05,2026-08-14,PayPal,4.6
27,1028,Henry,Coventry,Clothing,Coat,1,95.0,0.15,2026-08-14,Card,4.3

In [ ]:
#19. Find orders from London AND Category = Electronics.
df[(df['City']=='London') & (df['Category']=='Electronics')]

,OrderID,Customer,City,Category,Product,Quantity,UnitPrice,Discount,OrderDate,PaymentMethod,Rating
0,1001,Amit,London,Electronics,Headphones,2,45.0,0.10,2026-08-01,Card,4.5
6,1007,Noah,London,Electronics,Mouse,2,20.0,0.05,2026-08-04,PayPal,4.6
11,1012,Ethan,London,Electronics,Monitor,1,180.0,0.10,2026-08-06,PayPal,4.9
26,1027,Lily,London,Electronics,Power Bank,2,30.0,0.05,2026-08-14,PayPal,4.6

In [ ]:
#20. Find orders from Coventry OR Birmingham.
df[(df['City'] == 'Coventry') | (df['City']=='Birmingham')].sort_values(by='City')

,OrderID,Customer,City,Category,Product,Quantity,UnitPrice,Discount,OrderDate,PaymentMethod,Rating
1,1002,Sara,Birmingham,Clothing,Jacket,1,80.0,0.00,2026-08-01,PayPal,4.0
8,1009,Liam,Birmingham,Home,Chair,2,55.0,0.10,2026-08-05,Card,3.9
13,1014,Lucas,Birmingham,Home,Desk,1,120.0,0.15,2026-08-07,Card,4.4
18,1019,Freya,Birmingham,Grocery,Bread,3,2.2,0.00,2026-08-10,Cash,NaN
23,1024,George,Birmingham,Electronics,Laptop Stand,1,32.0,0.05,2026-08-12,Card,4.8
28,1029,Evie,Birmingham,Home,Rug,1,65.0,0.00,2026-08-15,Card,4.1
3,1004,Priya,Coventry,Electronics,Keyboard,1,35.0,0.00,2026-08-02,Card,4.8
7,1008,Olivia,Coventry,Home,Lamp,1,25.0,0.00,2026-08-04,Card,4.2
12,1013,Sophia,Coventry,Grocery,Milk,6,1.5,0.00,2026-08-07,Card,4.3
17,1018,Leo,Coventry,Electronics,USB Cable,5,6.0,0.00,2026-08-09,Card,4.0
22,1023,Ella,Coventry,Grocery,Eggs,2,3.2,0.00,2026-08-12,Card,4.2
27,1028,Henry,Coventry,Clothing,Coat,1,95.0,0.15,2026-08-14,Card,4.3

In [ ]:
#21. Find orders where UnitPrice is between £30 and £80.
df[(df['UnitPrice']> 30]) & (df['UnitPrice']<80)]

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (972889172.py, line 2)

In [ ]:
df[(df['UnitPrice']>30) & (df['UnitPrice']<80)].sort_values(by='UnitPrice')

,OrderID,Customer,City,Category,Product,Quantity,UnitPrice,Discount,OrderDate,PaymentMethod,Rating
23,1024,George,Birmingham,Electronics,Laptop Stand,1,32.0,0.05,2026-08-12,Card,4.8
3,1004,Priya,Coventry,Electronics,Keyboard,1,35.0,0.00,2026-08-02,Card,4.8
21,1022,Harry,London,Clothing,Sweater,2,35.0,0.00,2026-08-11,PayPal,3.7
15,1016,Jack,Leeds,Clothing,Jeans,2,40.0,0.00,2026-08-08,Card,4.1
19,1020,Oscar,Manchester,Home,Shelf,2,45.0,0.05,2026-08-10,Card,4.6
0,1001,Amit,London,Electronics,Headphones,2,45.0,0.10,2026-08-01,Card,4.5
14,1015,Isla,Manchester,Electronics,Speaker,2,50.0,0.05,2026-08-08,Cash,3.8
8,1009,Liam,Birmingham,Home,Chair,2,55.0,0.10,2026-08-05,Card,3.9
20,1021,Amelia,Leeds,Electronics,Webcam,1,55.0,0.10,2026-08-11,Card,4.7
4,1005,David,Manchester,Clothing,Shoes,2,60.0,0.15,2026-08-03,Cash,4.1
28,1029,Evie,Birmingham,Home,Rug,1,65.0,0.00,2026-08-15,Card,4.1
24,1025,Chloe,Manchester,Home,Mirror,1,70.0,0.10,2026-08-13,Cash,4.4

In [ ]:
#22. Find orders where PaymentMethod is Card or PayPal.
df['PaymentMethod'] = df.PaymentMethod.str.strip()

In [ ]:
df[(df['PaymentMethod']=='Card') | (df['PaymentMethod']=='PayPal')]

,OrderID,Customer,City,Category,Product,Quantity,UnitPrice,Discount,OrderDate,PaymentMethod,Rating
0,1001,Amit,London,Electronics,Headphones,2,45.0,0.10,2026-08-01,Card,4.5
1,1002,Sara,Birmingham,Clothing,Jacket,1,80.0,0.00,2026-08-01,PayPal,4.0
2,1003,John,London,Grocery,Coffee,3,8.5,0.05,2026-08-02,Card,3.5
3,1004,Priya,Coventry,Electronics,Keyboard,1,35.0,0.00,2026-08-02,Card,4.8
5,1006,Emma,Leeds,Grocery,Tea,4,5.0,0.00,2026-08-03,Card,NaN
6,1007,Noah,London,Electronics,Mouse,2,20.0,0.05,2026-08-04,PayPal,4.6
7,1008,Olivia,Coventry,Home,Lamp,1,25.0,0.00,2026-08-04,Card,4.2
8,1009,Liam,Birmingham,Home,Chair,2,55.0,0.10,2026-08-05,Card,3.9
10,1011,Mia,Leeds,Clothing,T-Shirt,3,18.0,0.05,2026-08-06,Card,4.7
11,1012,Ethan,London,Electronics,Monitor,1,180.0,0.10,2026-08-06,PayPal,4.9
12,1013,Sophia,Coventry,Grocery,Milk,6,1.5,0.00,2026-08-07,Card,4.3
13,1014,Lucas,Birmingham,Home,Desk,1,120.0,0.15,2026-08-07,Card,4.4
15,1016,Jack,Leeds,Clothing,Jeans,2,40.0,0.00,2026-08-08,Card,4.1
16,1017,Grace,London,Home,Cushion,4,12.0,0.10,2026-08-09,PayPal,4.5
17,1018,Leo,Coventry,Electronics,USB Cable,5,6.0,0.00,2026-08-09,Card,4.0
19,1020,Oscar,Manchester,Home,Shelf,2,45.0,0.05,2026-08-10,Card,4.6
20,1021,Amelia,Leeds,Electronics,Webcam,1,55.0,0.10,2026-08-11,Card,4.7
21,1022,Harry,London,Clothing,Sweater,2,35.0,0.00,2026-08-11,PayPal,3.7
22,1023,Ella,Coventry,Grocery,Eggs,2,3.2,0.00,2026-08-12,Card,4.2
23,1024,George,Birmingham,Electronics,Laptop Stand,1,32.0,0.05,2026-08-12,Card,4.8
25,1026,Arthur,Leeds,Grocery,Pasta,4,2.5,0.00,2026-08-13,Card,3.9
26,1027,Lily,London,Electronics,Power Bank,2,30.0,0.05,2026-08-14,PayPal,4.6
27,1028,Henry,Coventry,Clothing,Coat,1,95.0,0.15,2026-08-14,Card,4.3
28,1029,Evie,Birmingham,Home,Rug,1,65.0,0.00,2026-08-15,Card,4.1

In [ ]:
#23. Find customers whose Rating is greater than or equal to 4.5.
df['Rating'] = df.Rating.astype('float')
df[(df['Rating'] >= 4.5)].sort_values('Rating')

,OrderID,Customer,City,Category,Product,Quantity,UnitPrice,Discount,OrderDate,PaymentMethod,Rating
0,1001,Amit,London,Electronics,Headphones,2,45.0,0.10,2026-08-01,Card,4.5
16,1017,Grace,London,Home,Cushion,4,12.0,0.10,2026-08-09,PayPal,4.5
19,1020,Oscar,Manchester,Home,Shelf,2,45.0,0.05,2026-08-10,Card,4.6
6,1007,Noah,London,Electronics,Mouse,2,20.0,0.05,2026-08-04,PayPal,4.6
26,1027,Lily,London,Electronics,Power Bank,2,30.0,0.05,2026-08-14,PayPal,4.6
20,1021,Amelia,Leeds,Electronics,Webcam,1,55.0,0.10,2026-08-11,Card,4.7
10,1011,Mia,Leeds,Clothing,T-Shirt,3,18.0,0.05,2026-08-06,Card,4.7
3,1004,Priya,Coventry,Electronics,Keyboard,1,35.0,0.00,2026-08-02,Card,4.8
23,1024,George,Birmingham,Electronics,Laptop Stand,1,32.0,0.05,2026-08-12,Card,4.8
11,1012,Ethan,London,Electronics,Monitor,1,180.0,0.10,2026-08-06,PayPal,4.9

In [ ]:
#24. Sort the complete DataFrame by UnitPrice ascending.
df.sort_values(by='UnitPrice')

,OrderID,Customer,City,Category,Product,Quantity,UnitPrice,Discount,OrderDate,PaymentMethod,Rating
12,1013,Sophia,Coventry,Grocery,Milk,6,1.5,0.00,2026-08-07,Card,4.3
18,1019,Freya,Birmingham,Grocery,Bread,3,2.2,0.00,2026-08-10,Cash,NaN
25,1026,Arthur,Leeds,Grocery,Pasta,4,2.5,0.00,2026-08-13,Card,3.9
29,1030,Charlie,Manchester,Grocery,Juice,3,2.8,0.00,2026-08-15,Cash,4.0
22,1023,Ella,Coventry,Grocery,Eggs,2,3.2,0.00,2026-08-12,Card,4.2
9,1010,Ava,Manchester,Grocery,Rice,5,3.5,0.00,2026-08-05,Cash,4.0
5,1006,Emma,Leeds,Grocery,Tea,4,5.0,0.00,2026-08-03,Card,NaN
17,1018,Leo,Coventry,Electronics,USB Cable,5,6.0,0.00,2026-08-09,Card,4.0
2,1003,John,London,Grocery,Coffee,3,8.5,0.05,2026-08-02,Card,3.5
16,1017,Grace,London,Home,Cushion,4,12.0,0.10,2026-08-09,PayPal,4.5
10,1011,Mia,Leeds,Clothing,T-Shirt,3,18.0,0.05,2026-08-06,Card,4.7
6,1007,Noah,London,Electronics,Mouse,2,20.0,0.05,2026-08-04,PayPal,4.6
7,1008,Olivia,Coventry,Home,Lamp,1,25.0,0.00,2026-08-04,Card,4.2
26,1027,Lily,London,Electronics,Power Bank,2,30.0,0.05,2026-08-14,PayPal,4.6
23,1024,George,Birmingham,Electronics,Laptop Stand,1,32.0,0.05,2026-08-12,Card,4.8
3,1004,Priya,Coventry,Electronics,Keyboard,1,35.0,0.00,2026-08-02,Card,4.8
21,1022,Harry,London,Clothing,Sweater,2,35.0,0.00,2026-08-11,PayPal,3.7
15,1016,Jack,Leeds,Clothing,Jeans,2,40.0,0.00,2026-08-08,Card,4.1
0,1001,Amit,London,Electronics,Headphones,2,45.0,0.10,2026-08-01,Card,4.5
19,1020,Oscar,Manchester,Home,Shelf,2,45.0,0.05,2026-08-10,Card,4.6
14,1015,Isla,Manchester,Electronics,Speaker,2,50.0,0.05,2026-08-08,Cash,3.8
8,1009,Liam,Birmingham,Home,Chair,2,55.0,0.10,2026-08-05,Card,3.9
20,1021,Amelia,Leeds,Electronics,Webcam,1,55.0,0.10,2026-08-11,Card,4.7
4,1005,David,Manchester,Clothing,Shoes,2,60.0,0.15,2026-08-03,Cash,4.1
28,1029,Evie,Birmingham,Home,Rug,1,65.0,0.00,2026-08-15,Card,4.1
24,1025,Chloe,Manchester,Home,Mirror,1,70.0,0.10,2026-08-13,Cash,4.4
1,1002,Sara,Birmingham,Clothing,Jacket,1,80.0,0.00,2026-08-01,PayPal,4.0
27,1028,Henry,Coventry,Clothing,Coat,1,95.0,0.15,2026-08-14,Card,4.3
13,1014,Lucas,Birmingham,Home,Desk,1,120.0,0.15,2026-08-07,Card,4.4
11,1012,Ethan,London,Electronics,Monitor,1,180.0,0.10,2026-08-06,PayPal,4.9

In [ ]:
#25. Sort by Quantity descending.
df.sort_values(by='Quantity', ascending=False)

,OrderID,Customer,City,Category,Product,Quantity,UnitPrice,Discount,OrderDate,PaymentMethod,Rating
12,1013,Sophia,Coventry,Grocery,Milk,6,1.5,0.00,2026-08-07,Card,4.3
9,1010,Ava,Manchester,Grocery,Rice,5,3.5,0.00,2026-08-05,Cash,4.0
17,1018,Leo,Coventry,Electronics,USB Cable,5,6.0,0.00,2026-08-09,Card,4.0
5,1006,Emma,Leeds,Grocery,Tea,4,5.0,0.00,2026-08-03,Card,NaN
16,1017,Grace,London,Home,Cushion,4,12.0,0.10,2026-08-09,PayPal,4.5
25,1026,Arthur,Leeds,Grocery,Pasta,4,2.5,0.00,2026-08-13,Card,3.9
18,1019,Freya,Birmingham,Grocery,Bread,3,2.2,0.00,2026-08-10,Cash,NaN
10,1011,Mia,Leeds,Clothing,T-Shirt,3,18.0,0.05,2026-08-06,Card,4.7
2,1003,John,London,Grocery,Coffee,3,8.5,0.05,2026-08-02,Card,3.5
29,1030,Charlie,Manchester,Grocery,Juice,3,2.8,0.00,2026-08-15,Cash,4.0
8,1009,Liam,Birmingham,Home,Chair,2,55.0,0.10,2026-08-05,Card,3.9
6,1007,Noah,London,Electronics,Mouse,2,20.0,0.05,2026-08-04,PayPal,4.6
0,1001,Amit,London,Electronics,Headphones,2,45.0,0.10,2026-08-01,Card,4.5
4,1005,David,Manchester,Clothing,Shoes,2,60.0,0.15,2026-08-03,Cash,4.1
26,1027,Lily,London,Electronics,Power Bank,2,30.0,0.05,2026-08-14,PayPal,4.6
21,1022,Harry,London,Clothing,Sweater,2,35.0,0.00,2026-08-11,PayPal,3.7
22,1023,Ella,Coventry,Grocery,Eggs,2,3.2,0.00,2026-08-12,Card,4.2
15,1016,Jack,Leeds,Clothing,Jeans,2,40.0,0.00,2026-08-08,Card,4.1
14,1015,Isla,Manchester,Electronics,Speaker,2,50.0,0.05,2026-08-08,Cash,3.8
19,1020,Oscar,Manchester,Home,Shelf,2,45.0,0.05,2026-08-10,Card,4.6
1,1002,Sara,Birmingham,Clothing,Jacket,1,80.0,0.00,2026-08-01,PayPal,4.0
3,1004,Priya,Coventry,Electronics,Keyboard,1,35.0,0.00,2026-08-02,Card,4.8
13,1014,Lucas,Birmingham,Home,Desk,1,120.0,0.15,2026-08-07,Card,4.4
11,1012,Ethan,London,Electronics,Monitor,1,180.0,0.10,2026-08-06,PayPal,4.9
7,1008,Olivia,Coventry,Home,Lamp,1,25.0,0.00,2026-08-04,Card,4.2
20,1021,Amelia,Leeds,Electronics,Webcam,1,55.0,0.10,2026-08-11,Card,4.7
24,1025,Chloe,Manchester,Home,Mirror,1,70.0,0.10,2026-08-13,Cash,4.4
23,1024,George,Birmingham,Electronics,Laptop Stand,1,32.0,0.05,2026-08-12,Card,4.8
27,1028,Henry,Coventry,Clothing,Coat,1,95.0,0.15,2026-08-14,Card,4.3
28,1029,Evie,Birmingham,Home,Rug,1,65.0,0.00,2026-08-15,Card,4.1

In [ ]:
#26. Sort first by City and then by UnitPrice descending.
df.sort_values(by=['City', 'UnitPrice'], ascending=[True, False])

,OrderID,Customer,City,Category,Product,Quantity,UnitPrice,Discount,OrderDate,PaymentMethod,Rating
13,1014,Lucas,Birmingham,Home,Desk,1,120.0,0.15,2026-08-07,Card,4.4
1,1002,Sara,Birmingham,Clothing,Jacket,1,80.0,0.00,2026-08-01,PayPal,4.0
28,1029,Evie,Birmingham,Home,Rug,1,65.0,0.00,2026-08-15,Card,4.1
8,1009,Liam,Birmingham,Home,Chair,2,55.0,0.10,2026-08-05,Card,3.9
23,1024,George,Birmingham,Electronics,Laptop Stand,1,32.0,0.05,2026-08-12,Card,4.8
18,1019,Freya,Birmingham,Grocery,Bread,3,2.2,0.00,2026-08-10,Cash,NaN
27,1028,Henry,Coventry,Clothing,Coat,1,95.0,0.15,2026-08-14,Card,4.3
3,1004,Priya,Coventry,Electronics,Keyboard,1,35.0,0.00,2026-08-02,Card,4.8
7,1008,Olivia,Coventry,Home,Lamp,1,25.0,0.00,2026-08-04,Card,4.2
17,1018,Leo,Coventry,Electronics,USB Cable,5,6.0,0.00,2026-08-09,Card,4.0
22,1023,Ella,Coventry,Grocery,Eggs,2,3.2,0.00,2026-08-12,Card,4.2
12,1013,Sophia,Coventry,Grocery,Milk,6,1.5,0.00,2026-08-07,Card,4.3
20,1021,Amelia,Leeds,Electronics,Webcam,1,55.0,0.10,2026-08-11,Card,4.7
15,1016,Jack,Leeds,Clothing,Jeans,2,40.0,0.00,2026-08-08,Card,4.1
10,1011,Mia,Leeds,Clothing,T-Shirt,3,18.0,0.05,2026-08-06,Card,4.7
5,1006,Emma,Leeds,Grocery,Tea,4,5.0,0.00,2026-08-03,Card,NaN
25,1026,Arthur,Leeds,Grocery,Pasta,4,2.5,0.00,2026-08-13,Card,3.9
11,1012,Ethan,London,Electronics,Monitor,1,180.0,0.10,2026-08-06,PayPal,4.9
0,1001,Amit,London,Electronics,Headphones,2,45.0,0.10,2026-08-01,Card,4.5
21,1022,Harry,London,Clothing,Sweater,2,35.0,0.00,2026-08-11,PayPal,3.7
26,1027,Lily,London,Electronics,Power Bank,2,30.0,0.05,2026-08-14,PayPal,4.6
6,1007,Noah,London,Electronics,Mouse,2,20.0,0.05,2026-08-04,PayPal,4.6
16,1017,Grace,London,Home,Cushion,4,12.0,0.10,2026-08-09,PayPal,4.5
2,1003,John,London,Grocery,Coffee,3,8.5,0.05,2026-08-02,Card,3.5
24,1025,Chloe,Manchester,Home,Mirror,1,70.0,0.10,2026-08-13,Cash,4.4
4,1005,David,Manchester,Clothing,Shoes,2,60.0,0.15,2026-08-03,Cash,4.1
14,1015,Isla,Manchester,Electronics,Speaker,2,50.0,0.05,2026-08-08,Cash,3.8
19,1020,Oscar,Manchester,Home,Shelf,2,45.0,0.05,2026-08-10,Card,4.6
9,1010,Ava,Manchester,Grocery,Rice,5,3.5,0.00,2026-08-05,Cash,4.0
29,1030,Charlie,Manchester,Grocery,Juice,3,2.8,0.00,2026-08-15,Cash,4.0

In [ ]:
#27. Display the top 5 most expensive orders by UnitPrice.

In [ ]:
df.sort_values('UnitPrice',ascending =False).head(5)

,OrderID,Customer,City,Category,Product,Quantity,UnitPrice,Discount,OrderDate,PaymentMethod,Rating
11,1012,Ethan,London,Electronics,Monitor,1,180.0,0.10,2026-08-06,PayPal,4.9
13,1014,Lucas,Birmingham,Home,Desk,1,120.0,0.15,2026-08-07,Card,4.4
27,1028,Henry,Coventry,Clothing,Coat,1,95.0,0.15,2026-08-14,Card,4.3
1,1002,Sara,Birmingham,Clothing,Jacket,1,80.0,0.00,2026-08-01,PayPal,4.0
24,1025,Chloe,Manchester,Home,Mirror,1,70.0,0.10,2026-08-13,Cash,4.4

In [ ]:
## CLEANING

In [ ]:
#28. Check how many missing values exist in each column.
df.isnull().sum()

OrderID          0
Customer         0
City             0
Category         0
Product          0
Quantity         0
UnitPrice        0
Discount         0
OrderDate        0
PaymentMethod    0
Rating           2
dtype: int64

In [ ]:
#29. Identify rows where Rating is missing.
df['Rating'].isnull()

0     False
1     False
2     False
3     False
4     False
5      True
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18     True
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
Name: Rating, dtype: bool

In [ ]:
#30. Fill missing Rating values with the average rating.
df.fillna(df['Rating'].mean(), inplace=True)

In [ ]:
df.isnull.

AttributeError: 'function' object has no attribute 'sum'

In [ ]:
students = [
    {"name": "Alice", "scores": [85, 90, 78]},
    {"name": "Bob", "scores": [92, 88, 95]},
    {"name": "Charlie", "scores": [76, 82, 80]}
]

In [ ]:
for i in students:
  print(i)

{'name': 'Alice', 'scores': [85, 90, 78]}
{'name': 'Bob', 'scores': [92, 88, 95]}
{'name': 'Charlie', 'scores': [76, 82, 80]}