<a href="https://colab.research.google.com/github/ambreenkhurrum-lgtm/ITC/blob/main/Python_Day2_Advanced_Data_Engineering_Live_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Day 2
## Advanced Python + Data Engineering

Topics:
- Day 1 recap
- Lambda, map, filter, comprehensions
- Exception handling
- File handling
- CSV & JSON
- Modules, packages, pip, virtual environments
- Environment variables and logging
- OOP basics and advanced OOP
- Inheritance and polymorphism
- Decorators
- Generators
- Multithreading
- Multiprocessing
- APIs
- Database connectivity
- Pandas
- Pandas joins and transformations
- Mini ETL project

## 1. Day 1 Recap
Quick revision of variables, collections, conditions, loops, and functions.

In [ ]:
employees = [
    {"name": "John", "salary": 50000},
    {"name": "Sam", "salary": 65000},
    {"name": "Alex", "salary": 42000}
]

for emp in employees:
    if emp["salary"] > 50000:
        print(emp["name"])

Sam

## 2. Lambda Functions
A lambda is a small anonymous function, useful for short one-expression operations.

In [ ]:
square = lambda x: x * x
print(square(5))

add = lambda a, b: a + b
print(add(10, 20))

## 3. map()
`map()` applies a function to every item in an iterable.

In [ ]:
amounts = [100, 200, 300, 400]
with_tax = list(map(lambda x: x * 1.20, amounts))
print(with_tax)

[120.0, 240.0, 360.0, 480.0]

In [ ]:
numbers = [1,2,3,4]
square = list(map(lambda x: x * x, numbers))
print(square)

[1, 4, 9, 16]

## 4. filter()
`filter()` keeps only items for which a condition is True.

In [ ]:
transactions = [50, 1200, 400, 2500, 80]
high_value = list(filter(lambda x: x > 1000, transactions))
print(high_value)

[1200, 2500]

In [ ]:
#print the even numbers
numbers = [1,2,3,4,5,6,7,8,9]

## 5. Comprehension Recap
Comprehensions are often a more readable alternative to map/filter for simple transformations.

In [ ]:
transactions = [50, 1200, 400, 2500, 80]
high_value = [x for x in transactions if x > 1000]
print(high_value)

[1200, 2500]

## 6. Exception Handling
Use `try/except` to handle expected errors without crashing the whole program.

In [ ]:
try:
    value = int("abc")
except ValueError as error:
    print("Invalid integer:", error)
else:
    print("Conversion succeeded:", value)
finally:
    print("This always executes")

Invalid integer: invalid literal for int() with base 10: 'abc'
This always executes

### Multiple Exception Types

In [ ]:
records = [{"amount":"100"}, {"amount":None}, {}, {"amount":"bad"}]

for record in records:
    try:
        amount = float(record["amount"])
        print("Processed:", amount)
    except (KeyError, TypeError, ValueError) as error:
        print("Rejected:", record, "|", type(error).__name__)

Processed: 100.0
Rejected: {'amount': None} | TypeError
Rejected: {} | KeyError
Rejected: {'amount': 'bad'} | ValueError

## 7. File Handling
`open()` works with files. Common modes are `r`, `w`, and `a`. `with` , 'x' automatically closes the file.

In [ ]:
with open("pipeline_log.txt", "w") as file:
    file.write("Pipeline started\n")

with open("pipeline_log.txt", "a") as file:
    file.write("100 records processed\n")

with open("pipeline_log.txt", "r") as file:
    print(file.read())

Pipeline started
100 records processed

## 8. CSV
CSV is a common tabular data format.

In [ ]:
import csv

rows = [
    ["id", "name", "amount"],
    [1, "John", 100],
    [2, "Sam", 250],
    [3, "Alex", 500]
]

with open("transactions.csv", "w", newline="") as file:
    csv.writer(file).writerows(rows)

with open("transactions.csv", "r") as file:
    for row in csv.reader(file):
        print(row)

['id', 'name', 'amount']
['1', 'John', '100']
['2', 'Sam', '250']
['3', 'Alex', '500']

In [ ]:
file_path = ''

## 9. JSON
JSON represents structured/semi-structured data using objects and arrays. Python dictionaries map naturally to JSON objects.

In [ ]:
import json

customer = {
    "id": 101,
    "name": "John",
    "address": {"city": "London", "postcode": "E1 1AA"},
    "orders": [{"id": 1, "amount": 100}, {"id": 2, "amount": 250}]
}

with open("customer.json", "w") as file:
    json.dump(customer, file, indent=2)

with open("customer.json", "r") as file:
    data = json.load(file)

print(data["address"]["city"])
print(data["orders"][0]["amount"])

## 10. Modules & Packages
A module is usually a Python file. A package groups modules. Python also provides standard-library modules.

In [ ]:
import math
import os
from datetime import datetime

print(math.sqrt(81))
print(datetime.now())
print(os.getcwd())

9.0
2026-09-08 14:25:04.289124
/content

### pip and Virtual Environments
`pip` installs packages. A virtual environment isolates project dependencies.

In [ ]:
# Colab example:
# !pip install requests

# Local-machine examples (do not run these as Python):
# python -m venv myenv
# Windows: myenv\Scripts\activate
# macOS/Linux: source myenv/bin/activate

## 11. Environment Variables
Environment variables keep configuration outside application logic.

In [ ]:
import os

os.environ["PIPELINE_ENV"] = "DEV"
environment = os.getenv("PIPELINE_ENV")

print(environment)

## 12. Logging
Logging records pipeline events at levels such as DEBUG, INFO, WARNING, ERROR and CRITICAL.

In [ ]:
import logging

logging.basicConfig(level=logging.INFO, force=True)
logger = logging.getLogger("data_pipeline")

logger.info("Pipeline started")
logger.warning("Null values detected")
logger.error("Example load failure")

## 13. OOP Basics
A class is a blueprint; an object is an instance. `__init__` initializes object attributes.

In [ ]:
class Employee:
    def __init__(self, name, salary):
        self.name = name
        self.salary = salary

    def display(self):
        print(f"{self.name}: £{self.salary}")

emp = Employee("John", 55000)
emp.display()

John: £55000

## 14. Encapsulation / Advanced OOP
OOP can group data and behavior and control how internal state is accessed.

In [ ]:
class BankAccount:
    def __init__(self, owner, balance):
        self.owner = owner
        self._balance = balance

    def deposit(self, amount):
        if amount > 0:
            self._balance += amount

    def get_balance(self):
        return self._balance

account = BankAccount("John", 1000)
account.deposit(500)
print(account.get_balance())

1500

## 15. Inheritance
Inheritance lets a child class reuse and extend a parent class.

In [ ]:
class DataSource:
    def connect(self):
        print("Connecting to data source")

class DatabaseSource(DataSource):
    def query(self):
        print("Running SQL query")

db = DatabaseSource()
db.connect()
db.query()

In [ ]:
add example of types inheritance

## 16. Polymorphism
Different classes can provide the same method name with different implementations.

In [ ]:
class CSVSource:
    def read(self):
        return "Reading CSV"

class JSONSource:
    def read(self):
        return "Reading JSON"

sources = [CSVSource(), JSONSource()]

for source in sources:
    print(source.read())

In [ ]:
#Abstraction:
class ATM:

    def withdraw(self, amount):
        self.__check_balance(amount)
        self.__verify_pin()
        print("Please collect your cash")

    def __check_balance(self, amount):
        print("Checking account balance...")

    def __verify_pin(self):
        print("Verifying PIN...")


atm = ATM()
atm.withdraw(100)

Checking account balance...
Verifying PIN...
Please collect your cash

## 17. Decorators
A decorator wraps a function to add behavior without rewriting the original function.

In [ ]:
def log_execution(func):
    def wrapper(*args, **kwargs):
        print(f"Starting {func.__name__}")
        result = func(*args, **kwargs)
        print(f"Finished {func.__name__}")
        return result

    return wrapper

@log_execution
def transform_data():
    print("Transforming data...")

transform_data()

Starting transform_data
Transforming data...
Finished transform_data

In [ ]:
# read about *args, **kwargs

## 18. Generators
A generator produces values one at a time using `yield`, instead of building the entire result in memory.

In [ ]:
def batch(data, batch_size):
    for i in range(0, len(data), batch_size):
        yield data[i:i + batch_size]

records = list(range(1, 11))

for batch in batch(records, 3):
    print("Batch:", batch)

Batch: [1, 2, 3]
Batch: [4, 5, 6]
Batch: [7, 8, 9]
Batch: [10]

## 19. Multithreading
Threads can be useful for I/O-bound work such as waiting for APIs or files.

In [ ]:
from concurrent.futures import ThreadPoolExecutor
import time

def fetch_source(source):
    time.sleep(1)
    return f"Finished {source}"

sources = ["API-1", "API-2", "API-3"]

with ThreadPoolExecutor(max_workers=3) as executor:
    results = list(executor.map(fetch_source, sources))

print(results)

## 20. Multiprocessing
Processes can use multiple CPU cores for CPU-bound work. In notebooks, top-level worker functions are safest.

In [ ]:
# This example is intentionally small for live teaching.
from multiprocessing import cpu_count

print("Available CPU cores:", cpu_count())

# Typical local-script pattern:
# from multiprocessing import Pool
#
# def square(x):
#     return x * x
#
# if __name__ == "__main__":
#     with Pool(2) as pool:
#         print(pool.map(square, [1, 2, 3, 4]))

## 21. APIs
The `requests` package can call HTTP APIs and parse JSON responses.

In [ ]:
import requests

response = requests.get(
    "https://jsonplaceholder.typicode.com/users",
    timeout=10
)

print("Status:", response.status_code)

if response.ok:
    users = response.json()
    for user in users[:3]:
        print(user["id"], user["name"], user["email"])

## 22
. Pandas Basics
Pandas uses DataFrames for tabular data processing.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "id": [1, 2, 3, 4, 4],
    "department": ["IT", "HR", "IT", "Finance", "Finance"],
    "salary": [55000, None, 65000, 58000, 58000]
})

display(df)
print(df.shape)
print(df.columns.tolist())
print(df.dtypes)

   id department   salary
0   1         IT  55000.0
1   2         HR      NaN
2   3         IT  65000.0
3   4    Finance  58000.0
4   4    Finance  58000.0

(5, 3)
['id', 'department', 'salary']
id              int64
department     object
salary        float64
dtype: object

### Filtering, Nulls, Duplicates and Sorting

In [ ]:
clean = df.drop_duplicates().copy()
clean["salary"] = clean["salary"].fillna(0)

display(clean[clean["salary"] > 50000])
display(clean.sort_values("salary", ascending=False))

   id department   salary
0   1         IT  55000.0
2   3         IT  65000.0
3   4    Finance  58000.0

   id department   salary
2   3         IT  65000.0
3   4    Finance  58000.0
0   1         IT  55000.0
1   2         HR      0.0

### groupby and Aggregation

In [ ]:
summary = (
    clean.groupby("department")
         .agg(
             average_salary=("salary", "mean"),
             employee_count=("id", "count")
         )
         .reset_index()
)

display(summary)

## 24. Pandas Joins & Transformations
`merge()` joins DataFrames. Other common transformations include rename, fillna, dropna and drop_duplicates.

In [ ]:
customers = pd.DataFrame({
    "customer_id": [1, 2, 3],
    "customer_name": ["John", "Sam", "Alex"]
})

transactions = pd.DataFrame({
    "transaction_id": [101, 102, 103, 104],
    "customer_id": [1, 1, 2, 3],
    "amount": [100, 150, None, 300]
})

transactions["amount"] = transactions["amount"].fillna(0)
transactions = transactions.rename(columns={"amount": "transaction_amount"})

joined = customers.merge(transactions, on="customer_id", how="left")
display(joined)

## 25. Mini ETL Project
Extract from CSV → clean/transform → aggregate → load to output CSV.

In [ ]:
import pandas as pd

raw = pd.DataFrame({
    "transaction_id": [1, 2, 2, 3, 4, 5],
    "customer": ["John", "Sam", "Sam", "Alex", "Maria", "Tom"],
    "city": ["London", "Coventry", "Coventry", "London", "Birmingham", "London"],
    "amount": [100, 250, 250, None, 500, 50]
})

raw.to_csv("raw_sales.csv", index=False)
display(raw)

In [ ]:
# EXTRACT
df = pd.read_csv("raw_sales.csv")

# TRANSFORM
df = df.drop_duplicates()
df["amount"] = df["amount"].fillna(0)
df = df[df["amount"] > 0]

city_sales = (
    df.groupby("city")
      .agg(
          total_sales=("amount", "sum"),
          transaction_count=("transaction_id", "count")
      )
      .reset_index()
)

display(city_sales)

In [ ]:
# LOAD
city_sales.to_csv("city_sales_summary.csv", index=False)
print("ETL completed: city_sales_summary.csv created")

# Final Teaching Connection

```text
Files / APIs / Databases
          ↓
        Python
          ↓
Exceptions + Logging
          ↓
Functions / OOP
          ↓
Pandas Transformations
          ↓
       ETL Output
          ↓
PySpark / Airflow / Cloud Data Engineering
```